version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: inovix-mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_container:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpassword

  mongo-express:
    image: mongo-express:1.0.0-alpha.4
    container_name: inovix-mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: adminpassword
      ME_CONFIG_MONGODB_URL: mongodb://admin:adminpassword@mongodb:27017/
    depends_on:
      - mongodb

volumes:
  mongodb_data_container: